services:
  dog:
    build:
      context: .
      target: builder
    container_name: http_dog
    environment:
      PORT: 80
    ports:
      - 0.0.0.0:80:80
      # - 92.205.108.193:80:80
    restart: "always"

